name: Go Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        go-os: [ windows-latest, ubuntu-latest ]
        go-version: [ 1.20 ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: go mod download

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build Go Application
        run: |
          if [ ${{ matrix.go-os }} == 'windows-latest' ]; then
            GOOS=windows GOARCH=amd64 go build -o rattler.exe main.go
          else
            go build -o rattler main.go
          fi

      - name: Create and Upload Release
        id: create_upload_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            rattler${{ matrix.go-os == 'windows-latest' && '.exe' }}
            README_DEPLOY.md
            .rattler.yaml
